### ISSUE TITLE
Pre-size pixel shaders

### ISSUE THREAD

**Issue by adipose** [Aleksoid1978/VideoRenderer#13]
mpc-hc supports pre and post-size shaders.  madVR supports both, but mpc-vr only supports post resize shaders.

This leads to a result that in mpc-hc, mpc-vr only honors one kind of shader, which is confusing as both are possible to choose and add.

Is there any chance for support in the future?

**Comment by Aleksoid1978** [comment]
There is always a chance :)

**Comment by v0lt** [comment]
Write, why is this really necessary in your practice?

**Comment by adipose** [comment]
@clsid2 for comment

I suspect some shaders perform better on the source data than resized data. Resizing can cause artifacts which might decrease the quality of the shader output. But I wasn't involved in the decision to have both.

**Comment by clsid2** [comment]
Another reason was performance. Having to process a smaller amount of pixels in the shader.

**Comment by v0lt** [comment]
1. If we make custom shaders before resizing, then users will not be able to change the frame size using the DXVA2 and D3D11 video processors. A shader resize will be used, this will increase the load on the video card.
2. I do not see an urgent need to use custom shaders before resizing.

Therefore, I do not plan to do this. This will complicate the code and take time for more useful things.

**Comment by adipose** [comment]
I was reviewing shaders in mpc-hc and mpc-be, and 16-235 to 0-255 [SD].hlsl has an interesting comment in the mpc-be source:

// Run this shader before scaling.

This comment is not in the mpc-hc source (maybe it was removed), but it is interesting.  With MPC-VR we cannot follow the instructions of this shader.

**Comment by adipose** [comment]
I'm going to close this issue since there is no interest in supporting it.  For now we will push all pre-resize shaders to post-resize in mpc-hc, and make a note for users of mpc-vr.

**Comment by butterw** [comment]
Could the mpc-vr support for pre-resize shader issue be reconsidered ?

- Mpc-hc release v1.9.9 contains blur shaders (ex: Gaussian Blur 3x3.hlsl). For efficient blurring these shaders need to be used pre-resize in an upscaling scenario (a fixed 3x3 kernel has less blurring power at a higher resolution, a sharp upscaler might be the default and in addition there are also more pixels to blur). A user reported he needed to use the shader 6 times post-resize instead of one pre-resize (+he wasn't resizing to 4K).
- More generally, shader processing should typically be done pre-resize (it depends on the shader, like in Avisynth some filters are used pre-size others post-resize). 
- When upscaling, having less pixels to process is beneficial to performance. 
- On the requirement of shader upscalers with pre-resize shaders (vs hardware upscalers):  pre-resize shaders could be a user configurable option if there is a performance hit for users who don't use shaders. 

From testing on my intel igpu, D3D9 EX with DXVA2 VP is used by default for resizing with MPC-VR rather than shader resizers. However performance on my old cpu/igpu is still very decent at 1080p on pre-resized shader capable EVR-CP and from what I see in the shader profiler display in mpv, the impact of  user shaders is typically much larger than a resizer like bicubic.
