### ISSUE TITLE
Blurry / image distortion when downscaling with DXVA2/D3D11

### ISSUE THREAD

**Issue by Enigma-KT** [Aleksoid1978/VideoRenderer#140]
Video very blurry if "Use for resizing" is enabled in options under "DXVA2 and D3D11 video processor". I am downscaling 2160p to 1080p.

https://imgur.com/a/e9IgLvf

Download full resolution images to compare.

**Comment by v0lt** [comment]
D3D11 video processor scaling is implemented in the driver. Write about this to Nvidia.

**Comment by zybexXL** [comment]
Upscaling is also terrible now, it was not like this before (AMD GPU).

MadVR's upscaling with DXVA2 + DX11 is still high-quality, so I don't think it's a driver issue. Can you please quickly check? The issue is readily visible with a black screen with just some static white text on top (non-moving credits/opening scenes).

DX9, DXVA2 (similar to MadVR quality):
![image](https://github.com/user-attachments/assets/c7ca547c-a82f-4859-8254-671bb1f9cf1b)

DX11, "use DXVA2" enabled:
![image](https://github.com/user-attachments/assets/c3b14508-8058-44bb-bb08-9dc8eb6d9c8e)
