### ISSUE TITLE
Improve HDR tonemapping brightness

### ISSUE THREAD

**Issue by clsid2** [Aleksoid1978/VideoRenderer#143]
A common problem with current tonemapping is that the result is too dark on some monitors.

A solution would be to make `DISPLAY_LUMINANCE_PEAK` an input parameter in `fixconvert_pq_to_sdr.hlsl`. You can use [SetPixelShaderConstantF](https://learn.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-setpixelshaderconstantf) to pass such parameter value to the shader.
The display luminance can then be an option in the GUI. I would suggest naming it "target nits" like in Madvr. With value range between 50 and 200.

Maybe also make `SRC_LUMINANCE_PEAK` an input parameter. Default to 10000 like it is now. But perhaps use `MaxCLL` from HDR metadata instead when known?

Please don't close. I can do it in future if needed. But you can do it faster, as it shouldn't be difficult.

**Comment by v0lt** [comment]
I have a question. Has anyone tried changing DISPLAY_LUMINANCE_PEAK on different videos and displays? What was the result? Within what limits does it make sense to change this parameter?

**Comment by Aleksoid1978** [comment]
There is no need to leave this question.
If you have the desire/opportunity, make either a patch or a pull request.

**Comment by NBruderman** [comment]
@clsid2 Do you intend to make this patch? It seems like it could really beneficial

**Comment by v0lt** [comment]
> 50-200 seems good initial range to me. But range can always be increased if users need it.

You can take screenshots for the value 50 and 200 using samples from here - https://kodi.wiki/view/Samples
I suggest downloading one of these files:
HDR 10-bit HEVC 59.94fps (in MP4, Camp by Sony)
VP9 Profile 2 HDR 24fps The Redwoods (in MKV) (thanks @wesk05)
VP9 Profile 2 HDR 59.94fps The World in HDR (in MKV) (thanks @wesk05)

And the second question. Why don't you use the option to adjust brightness and contrast?

**Comment by v0lt** [comment]
50
![050](https://github.com/Aleksoid1978/VideoRenderer/assets/2035946/7672fca5-d8a3-4c52-bb85-f92ca4d2fb86)

125
![125](https://github.com/Aleksoid1978/VideoRenderer/assets/2035946/97473daa-5628-4e70-9324-8bf73b0a6d9f)

200
![200](https://github.com/Aleksoid1978/VideoRenderer/assets/2035946/243ae619-50fb-4059-8d82-92943d1e3a34)

125 looks best on my display.

**Comment by mightyhuhn** [comment]
i don't know how the tone mapping algorithm works in detail in mpcVR but for accurate tone mapping you need to know the target gamma and brightness.

in tone mapping there are 2 important part in it the "linear part" that's from 0 brightness to a knee point that depends on the peak brightness. this part is not compressed at all. that's why you can not just adjust the brightness because that will compress everything making the results wrong. same issue with just changing gamma.

after the knee point this part is actually tone mapped and compressed rolled of and what so ever only that part should change when the peak brightness is changed.

exposing peak brightness and if possible gamma will help quite a bit.
https://github.com/Aleksoid1978/VideoRenderer/blob/master/Shaders/d3d11/ps_convert_pq_to_sdr.hlsl
 color = pow(color, 1.0 / 2.2);

exposing that 2.2 should do the trick.
BTW. that's not sRGB.

**Comment by mightyhuhn** [comment]
what ever you have calibrated your device to that's why it should be configurable there is no one true number.
if not defined madVR guesses 2.2 so does mpv. so the 2.2 is what other renderer use which was a "good" start.

the spec is bt1886 today but that's quite out of scope because then you have to define the brightness and the black point too so i suggest to ignore bt1886 for now and it is not that i ever heard someone calibrate to it and stick to it using an LCD... bt1886 is 2.4 on an OLED for example and before bt1886 the "specification" was 2.4. so many will change this to 2.4 or 2.22 for sRGB approximation. some PJ user like to use 2.35.

gamma is the wild west everything between 1.8-2.6 can be used.

**Comment by mightyhuhn** [comment]
not this again :-)

bt 709 doesn't have a transfer function it only has a oetf which we should ignore. the spec it self tells us not to use the oetf as an eotf. don't believe me believe the specification:
https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.709-6-201506-I!!PDF-E.pdf
In typical production practice the encoding function of image sources is adjusted so that the final picture has the
desired look, as viewed on a reference monitor having the reference decoding function of Recommendation
ITU-R BT.1886, in the reference viewing environment defined in Recommendation ITU-R BT.2035.

we are supposed to use the production transfer function and that was everything but not that one.

the "gamma" in this link are not used: https://www.image-engineering.de/library/technotes/714-color-spaces-rec-709-vs-srgb
neither sRGB nor the bt709 "gamma" is a video gamma. EOTF gamma was not defined in bt 709 the first definition is BT1886: https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1886-0-201103-I!!PDF-E.pdf
and not only the exponent is 2.4 if black is 0 in the formula it will results in true gamma 2.4. the exponent does not matter because sRGB is also exponent of 2.4 but the ~gamma is 2.22 (cheap mans sRGB) and bt709 "gamma" is exponent 2.2 but the resulting gamma is ~1.961.
sRGB is used but not for video Microsoft thinks everything is sRGB. for SDR -> HDR Microsoft will use sRGB for SDR resulting in a wrong transfer function for video and a "correct" one for applications.

and the most important part here is we don't care about any of these we care about the real gamma of a display. and these are typically bt 1886, gamma 2.2-2.4 or sRGB. 
even if i wanted to use bt 709 "gamma" i will have a hard time to do so because even the very powerful displaycal does not support that out of the box and why would it do that.

want another proof from me why you should never use 1.961 bt 709.
take mpv use GPU-next make a screenshoot press s or S something. it will write 1.961 in the meta data and microsoft believes that in the photos app and tries to fix that resulting in quite the mess.

sorry i was not the person that forgot to define a EOTF when bt 709 was created.
i'm skipping a lot of stuff here like light condition in a room where under studio lightning 2.2 was used but the cinema presentation was using 2.4 in a dark room to look the same or how you can end up with 1.8 in a day light flooded room and what not. or another fun fact sRGB has a brightness of 80 needs ambient light with a white point of D50 while the white point is D65 the original sRGB is truncated resulting in a none continuous transfer function and banding. just madness.

**Comment by Aleksoid1978** [comment]
What a half-patch - no DX11, no UI.

**Comment by Aleksoid1978** [comment]
It's work only for VP or shaders too ?
UI - must apply chsnges "on fly"

**Comment by mightyhuhn** [comment]
sounds good enough to me so user can test if the algorithm can handle all of this properly in the first place.

**Comment by Aleksoid1978** [comment]
Debug:)

**Comment by v0lt** [comment]
My quick option if using a D3D11 video processor.
[LuminanceScale_1.diff.txt](https://github.com/Aleksoid1978/VideoRenderer/files/15287196/LuminanceScale_1.diff.txt)

**Comment by Aleksoid1978** [comment]
No - if no VP, use Shaders.

**Comment by Aleksoid1978** [comment]
When use Shaders - it's create from string and compile, see
https://github.com/Aleksoid1978/VideoRenderer/blob/master/Source/Shaders.cpp#L555

**Comment by Aleksoid1978** [comment]
UI it's no so easy, it's must change on the fly :)

**Comment by Aleksoid1978** [comment]
Some problem with save value when filter active, when playback.

**Comment by Aleksoid1978** [comment]
Good !

**Comment by Aleksoid1978** [comment]
Can you merge them into one and make PR ?

**Comment by Aleksoid1978** [comment]
![изображение](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/c124d454-3546-404d-b419-444df2f55963)
1 - Maybe better "SDR display nits" ? so variable "iTargetNits" -> "iSDRDisplayNits"
2 - Make available or not available depending on the "Convert to SDR" option.

About "hdrfactor -> LuminanceScale" - ok ).

**Comment by Aleksoid1978** [comment]
When you done - can you merge all code into one patch and upload ?

**Comment by mightyhuhn** [comment]
to bad no one is calibrating to gamma 2.2 these days.

**Comment by NBruderman** [comment]
> For using MaxCLL I need a few good sample files. But I got no reaction from anyone when asked on Doom9, so I guess nobody cares, and so I won't spend my time on that now. I don't have a collection of HDR movies.

@mightyhuhn do you have/can gather some samples of HDR content for this?

**Comment by adipose** [comment]
https://kodi.wiki/view/Samples

Some HDR samples are here.

**Comment by NBruderman** [comment]
> to bad no one is calibrating to gamma 2.2 these days.

So what values are being used?

**Comment by mightyhuhn** [comment]
> > For using MaxCLL I need a few good sample files. But I got no reaction from anyone when asked on Doom9, so I guess nobody cares, and so I won't spend my time on that now. I don't have a collection of HDR movies.
> 
> @mightyhuhn do you have/can gather some samples of HDR content for this?

my HDR knowledge is very limited(technically only). i just use the jav test sample he created for testing.
the doom9 guys are not really active anymore they are on AVS. the number there is also shrinking heavily.
not sure if they can be moved to look at static tone mapping.

> > to bad no one is calibrating to gamma 2.2 these days.
> 
> So what values are being used?
> 
> Also, I think in general exposing the gamma values could be more beneficial, however, I'm not a coder, and I have no idea how difficult or time consuming is to create such a patch, and if the benefits are noticeable enough.
> 
> @clsid2 @adipose do you think exposing gamma values is even worth the trouble?

bt 1886 is the first actual spec. 2.4 is be used for 20 years now. if you haven't calibrated your device just ignore this.

try madVR the idea is the same as the calibration tab. the gamma setting under "this display is already calibrated" will affect HDR tone mapping and does nothing to SDR.

after nots option is released i most likely just test it my self just compile a couple of version myself.

**Comment by NBruderman** [comment]
> > > For using MaxCLL I need a few good sample files. But I got no reaction from anyone when asked on Doom9, so I guess nobody cares, and so I won't spend my time on that now. I don't have a collection of HDR movies.
> > 
> > @mightyhuhn do you have/can gather some samples of HDR content for this?
> 
> my HDR knowledge is very limited(technically only). i just use the jav test sample he created for testing.
> the doom9 guys are not really active anymore they are on AVS. the number there is also shrinking heavily.
> not sure if they can be moved to look at static tone mapping.
> 
> > > to bad no one is calibrating to gamma 2.2 these days.
> > 
> > So what values are being used?
> > 
> > Also, I think in general exposing the gamma values could be more beneficial, however, I'm not a coder, and I have no idea how difficult or time consuming is to create such a patch, and if the benefits are noticeable enough.
> > 
> > @clsid2 @adipose do you think exposing gamma values is even worth the trouble?
> 
> bt 1886 is the first actual spec. 2.4 is be used for 20 years now. if you haven't calibrated your device just ignore this.
> 
> try madVR the idea is the same as the calibration tab. the gamma setting under "this display is already calibrated" will affect HDR tone mapping and does nothing to SDR.
> 
> after nots option is released i most likely just test it my self just compile a couple of version myself.

If you want to test the Nits patch, the latest K-lite update that got released today already includes it.

**Comment by Aleksoid1978** [comment]
If anyone is interested in checking HDR to SDR taking into account HDR metadata, check in Kodi with the HABLE method.
If something happens, you can try to transfer their developments into the project.

**Comment by Aleksoid1978** [comment]
I'm talking about the result, about the picture.
