### ISSUE TITLE
Color correction doesn't work

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#162]
Color correction settings in MPCBE/HC doesn't work with AMD GPU, when using MPCVR and the video is 10bit.
EVRCP fine with 10bit video.
MPCVR fine with only 8bit video.
AMD Ryzen 5 5600H.

**Comment by Aleksoid1978** [comment]
EVR CP - DX9, MPC VR - I think DX11, possible drivers fault.

**Comment by v0lt** [comment]
Disable DXVA2/D3D11 video processor for P010.

**Comment by bibsp** [comment]
Disabling DX11 in renderer or disabling P010 works.
![Screenshot (286)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/ba484a33-c403-44e1-825e-3e7554a80403)
![Screenshot (287)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/de337f33-24e7-4494-8349-2bf2463fbad7)
In both these cases color correction works.

**Comment by v0lt** [comment]
Added information to [Known Issues](https://github.com/Aleksoid1978/VideoRenderer/wiki/Known-Issues).

**Comment by v0lt** [comment]
@clsid2
I don't have that information.
I know that some AMD graphics adapters may have limitations when running P010. Some problems have been fixed in new versions of the driver. But I did not collect detailed information and we do not plan to add a list of adapters (and especially drivers) to the MPC VR code.
