### ISSUE TITLE
is there anyway can change lighting setting?

### ISSUE THREAD

**Issue by 4h4h270** [Aleksoid1978/VideoRenderer#27]
here's the statistics
https://i.imgur.com/aytGVGd.png

lighting is always dim* can't find anywhere to change it, makes picture too dark.

**Comment by Aleksoid1978** [comment]
Lighting - this is just information about data from the video stream, do not pay attention.
You try view HDR on SDR monitor, HDR -> SDR conversion in simple. Better view standard SDR video.

**Comment by clsid2** [comment]
madVR has option "target peak nits" that affects brightness of the HDR -> SDR tonemapping. Default is 200. But using for example 150 will give brighter image.

Is the current algorithm in MPCVR assuming a specific value for target nits? Then maybe in future it could offer simple choice between a few predefined values?

Is there some documentation somewhere for the current algorithm?

**Comment by Aleksoid1978** [comment]
Not planned add some likes features.

**Comment by Aleksoid1978** [comment]
But - patch are welcome:)

**Comment by v0lt** [comment]
View -> Options -> Color correction -> Brightness.

**Comment by clsid2** [comment]
Normal brightness option is not a good solution for this problem.

A simple short term solution would be to add a dropdown menu where you can choose value for DISPLAY_LUMINANCE_PEAK.
The "best" value depends a lot on the screen that is used. For example a projector can have pretty low peak nits (50). A normal monitor can handle the 125 that is current default, but many people will not have set monitor to highest brightness, because that is not comfortable for normal usage.

**Comment by Aleksoid1978** [comment]
Patch are welcome.

**Comment by v0lt** [comment]
> Normal brightness option is not a good solution for this problem.

I tried increasing the brightness by 25% and got a good result.
Try it yourself.

**Comment by 4h4h270** [comment]
> > Normal brightness option is not a good solution for this problem.
> 
> I tried increasing the brightness by 25% and got a good result.
> Try it yourself.

great, tried it works good
