### ISSUE TITLE
error X4014: cannot have gradient operations inside loops with divergent flow control

### ISSUE THREAD

**Issue by hooke007** [Aleksoid1978/VideoRenderer#37]
![Snipaste_2021-10-26_22-07-43](https://user-images.githubusercontent.com/41094733/138896053-1b2c86c8-5b7c-4aaa-8d87-a1a641fda6b5.jpg)

When running the `build_mpcvr.cmd` , I got this error.

ps. all the submodule of this repo is latest. so as visual studio.

**Comment by clsid2** [comment]
I ran into this as well after installing Win11 SDK. Solved it by adding Win10 SDK. Then strangely the errors stops, even when I tell VS to use the newer SDK in project file.

@Aleksoid1978 
Looking at the line in the code it complaints about, it is likely triggered by the 'float w` definition inside the loop. Putting definition outside the loop probably fixes the error. Can't test because that would require uninstalling SDK again.

**Comment by Aleksoid1978** [comment]
Use latest win11 sdk and all is ok

**Comment by clsid2** [comment]
Do you have just one SDK installed?

Here it happened with just 22621. Stopped after adding 19041. Even when VS is configured to use latest SDK for compiling the shaders.

Or do you mean it was fixed in 26100?

**Comment by v0lt** [comment]
Visual Studio 2019 v16.11.50, Windows SDK 10.0.19041.0 - no problems with compilation.

Windows SDKs older than 10.0.19041.0 are not supported.
