### ISSUE TITLE
OSD/UI/menus makes screen flicker when used in passthrough HDR mode + fullscreen

### ISSUE THREAD

**Issue by TinyTrbl** [Aleksoid1978/VideoRenderer#59]
OSD/UI/menu makes screen flicker (it *looks* like it goes back to SDR mode for a moment) when used in passthrough HDR mode + fullscreen
It does not flicker while in windowed passthrough HDR mode, only in fullscreen.
I think that i have tried every possible combination of MPC Video Renderer options without success.

Can you fix this somehow please?

MPC-BE 1.6.3
MPC Video Renderer 0.5.8.1877

![Clipboard Image](https://user-images.githubusercontent.com/45721596/178025242-19928107-b1aa-4871-8167-65ebf342d76f.png)

**Comment by Aleksoid1978** [comment]
Try latest MPC-BE + MPC VR - https://disk.yandex.ru/d/AjAXDDHtHRIELg

**Comment by cdeneen** [comment]
Hi, this happens to me as well. 

Windows 10 , 10bit color, full dynamic range, 4k, RGB output
Video player: MPC-HC 64-bit 1.9.2.2
MPC-VR: MPC Video Renderer 0.5.8.1877

Video file metadata:
```
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.2@Main
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10 compatible
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 53 s 950 ms
Bit rate                                 : 54.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 28.508 FPS
Maximum frame rate                       : 40.650 FPS
Real frame rate                          : 30.000 FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.217
Stream size                              : 347 MiB (100%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : UTC 2022-07-10 08:04:55
Tagged date                              : UTC 2022-07-10 08:04:55
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 200 cd/m2
Codec configuration box                  : hvcC
```
![image](https://user-images.githubusercontent.com/17381479/178244989-cd7acf06-4fe2-4493-b37a-8bbcc3be4482.png)


![image](https://user-images.githubusercontent.com/17381479/178245042-dfa08351-6479-4319-b4ab-c1b00417065b.png)

This might be connected to the gamma and saturation issue. When in full screen and an overlay object is displayed, for example the seek menu or right click menu, the video flickers once and the saturation and gamma increase. 

I also have two monitors, same model, when playing the HDR video full screen (monitor is in HDR mode, windows is in HDR mode) and I move the mouse to bring to focus an unrelated UI object , like this github page, on the second monitor (which is in sRGB mode, and Windows HDR is off) the same gamma and saturation issue occurs.  I tried to get a photo of the difference but it's very difficult due to post processing.

However, using the halo of a street light I was able to take a picture that shows the difference. The following picture was taken full screen, hdr, same video as metadata above. The video is paused so what you are seeing is the same frame from my phone camera. The only difference is I brought up the MPC-HC seek bar
![11](https://user-images.githubusercontent.com/17381479/178247063-5c2191a8-6e2b-4f4b-ac6c-9b72b5b1da2c.jpg)
![3322](https://user-images.githubusercontent.com/17381479/178247073-fdda2371-fdf2-4914-92b0-4519beaa89f4.jpg)

**Comment by Aleksoid1978** [comment]
I can't reproduce. For me it's good. Use Win11.
Maybe in Windows some Fullscreen optimization - i don't know.
Check in latest MPC-BE.

**Comment by clsid2** [comment]
Test if same problem also occurs with MadVR. In the past this problem was a common issue. I think it is driver related.

**Comment by cdeneen** [comment]
With the latest nvidia driver, video renderer, and mpc-be the HDR switching doesn't work. If I attempt to turn it on manually in Windows it will turn off when I play the video in mpc-bc

This doesn't happen in mpc-hc

I don't want to use Windows 11, this should work on 10

**Comment by Aleksoid1978** [comment]
If VR turn off HDR - it's only happened if video SDR. Upload you file(s) - i will check.
About On/Off HDR - VR use Windows API, and if something wrong - it's not VR issue.

**Comment by ancienttony** [comment]
Windows 11 24H2 still happens.
