### ISSUE TITLE
Toggle full screen transition improvement

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#63]
Older Versions

https://user-images.githubusercontent.com/98865389/187061455-4ac8a83d-0ed8-49b2-b1c0-ab2b37636a70.mp4

Latest Version

https://user-images.githubusercontent.com/98865389/187061467-f55a5c9d-349b-48a3-bd29-6aececd59169.mp4

The transition is not smooth as it was in previous versions of MPC-VR.

It's not urgent. Small glitch, I have noticed after updated to latest version of MPC-VR.
When developers have free time can look into it.

**Comment by v0lt** [comment]
> Older Versions
Latest Version
The transition is not smooth as it was in previous versions of MPC-VR.

I don't understand Old and Previous. And in one or two months I will not understand what Latest means. You wrote the bug report incorrectly.

"[Recommended MPC-BE 1.6.3 or newer.](https://github.com/Aleksoid1978/VideoRenderer)" Because we check and debug the MPC VR code in only one player - MPC-BE.

Take screenshots with statistics turned on. This gives a lot of additional information to the developer.

I also advise you to compare the settings in the old version and the new one.

**Comment by bibsp** [comment]
Latest means MPC-VR 0.6.3.1956
Old means MPC-VR 0.6.1.1931

All the settings were same in old and new one.

Tested with MPC-BE 1.6.3 also. There is no change in MPC-BE's behavior, no matter which version of MPCVR I use.
That means MPCBE+MPCVR 0.6.3.1956 or 0.6.1.1931 giving similar output.
So the whole bug report is invalid here.

After the 0.6.3.1956 update MPC-HC is giving this kind of jumping effect which was not there previously.



> we check and debug the MPC VR code in only one player - MPC-BE.

I did not know it. I thought you check with both MPC players. So created issue here.
You can close it.

**Comment by clsid2** [comment]
Perhaps related to the swap effect setting in MPCVR. Default was changed from discard to flip.

**Comment by bibsp** [comment]
> Perhaps related to the swap effect setting in MPCVR. Default was changed from discard to flip.

Yes. Thanks.

Issue solved.
